# Generated by Django 5.0.1 on 2024-01-31 13:50

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='sdfse123456789', length=123, max_length=99999, prefix='', unique=True),
        ),
    ]
