# Generated by Django 5.0.1 on 2024-01-31 13:51

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='sdfe12389', length=66, max_length=999, prefix='', unique=True),
        ),
    ]
