# Generated by Django 5.0.1 on 2024-01-31 13:53

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='sdfe12389', length=10, max_length=20, prefix='', unique=True),
        ),
    ]
