# Generated by Django 5.0.1 on 2024-01-31 13:55

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='sdfjhgcase88955124', length=10, max_length=20, prefix='cat', unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='sdfjhgcase88955124', length=10, max_length=20, prefix='ven', unique=True),
        ),
    ]
