# Generated by Django 5.0.1 on 2024-02-01 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_category_cid_alter_vendor_vid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
