# Generated by Django 5.0.1 on 2024-02-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_mfd_product_stock_count_product_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mfd',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_count',
            field=models.CharField(default='10', max_length=100),
        ),
    ]
