# Generated by Django 5.0.1 on 2024-02-22 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_product_mfd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
