# Generated by Django 5.0.1 on 2024-03-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_productreview_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='review',
            field=models.TextField(null=True),
        ),
    ]
