# Generated by Django 5.0.1 on 2024-03-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_productreview_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review',
            field=models.TextField(default=None, null=True),
        ),
    ]
