# Generated by Django 5.0.1 on 2024-02-18 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
