# Generated by Django 5.0.1 on 2024-02-18 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_product', '0002_remove_product_product_brand_delete_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributevalue',
            name='Attribute',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='product',
        ),
        migrations.RemoveField(
            model_name='variantimage',
            name='variant',
        ),
        migrations.DeleteModel(
            name='Atrribute',
        ),
        migrations.DeleteModel(
            name='AttributeValue',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
        migrations.DeleteModel(
            name='VariantImage',
        ),
    ]
