# Generated by Django 5.0.1 on 2024-02-19 11:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_product', '0004_product_featured_product_offer_price_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('89899'), max_digits=9),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('99999'), max_digits=9),
        ),
    ]
