# Generated by Django 5.0.1 on 2024-02-20 07:55

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_product', '0005_alter_product_offer_price_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=colorfield.fields.ColorField(default='black', image_field=None, max_length=25, samples=None),
        ),
    ]
