# Generated by Django 5.0.1 on 2024-02-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_product', '0006_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=49),
        ),
    ]
