# Generated by Django 5.0.1 on 2024-02-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_product', '0007_alter_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
