# Generated by Django 5.0.1 on 2024-02-25 04:00

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_product', '0010_attribute_attributevalue_productvariant_variantimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='black', image_field=None, max_length=25, samples=None),
        ),
    ]
