# Generated by Django 5.0.1 on 2024-02-25 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_product', '0012_rename_screen_size_productvariant_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='size',
        ),
    ]
