# Generated by Django 5.0.1 on 2024-02-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_product', '0013_remove_productvariant_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='featured',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
