# Generated by Django 5.0.1 on 2024-03-12 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_product', '0015_remove_product_product_status_and_more'),
        ('category_manage', '0002_remove_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_catg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='category_manage.category'),
        ),
    ]
