# Generated by Django 5.0.1 on 2024-03-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_product', '0017_alter_productvariant_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
