# Generated by Django 5.0.1 on 2024-04-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_product', '0019_alter_productvariant_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='soft_delete',
            field=models.BooleanField(default=False),
        ),
    ]
