# Generated by Django 5.0.1 on 2024-04-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_product', '0020_productvariant_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='soft_delete',
            field=models.BooleanField(default=False),
        ),
    ]
