# Generated by Django 5.0.1 on 2024-05-19 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_product', '0021_product_soft_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_to', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('Product_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ad_product.product')),
            ],
        ),
    ]
