# Generated by Django 5.0.1 on 2024-05-19 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_product', '0022_productoffer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoffer',
            old_name='Product_name',
            new_name='product_name',
        ),
    ]
