# Generated by Django 5.0.1 on 2024-06-09 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_product', '0023_rename_product_name_productoffer_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=30)),
                ('brand_img', models.ImageField(default='', upload_to='brand_logo/')),
                ('is_active', models.BooleanField(default=True)),
                ('soft_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ad_product.brand'),
        ),
    ]
