# Generated by Django 5.0.1 on 2024-05-21 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_referral_my_referral_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral',
            old_name='referral_code',
            new_name='referral_self',
        ),
    ]
