# Generated by Django 5.0.1 on 2024-05-21 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_rename_referral_code_referral_referral_self'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral',
            old_name='my_referral',
            new_name='referral',
        ),
    ]
