# Generated by Django 5.0.1 on 2024-05-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_rename_my_referral_referral_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral',
            field=models.CharField(blank=True, null=True),
        ),
    ]
