# Generated by Django 5.0.1 on 2024-02-18 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_manage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
