# Generated by Django 5.0.1 on 2024-05-06 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_manage', '0003_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_to', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('category_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='category_manage.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
