# Generated by Django 5.0.1 on 2024-05-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_remove_cart_coupon_cart_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=10000, max_digits=8, null=True),
        ),
    ]
