# Generated by Django 5.0.1 on 2024-02-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_order_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
