# Generated by Django 5.0.1 on 2024-03-30 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_cartorderitems_order_order_payment_orderitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
    ]
