# Generated by Django 5.0.1 on 2024-04-29 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_product', '0019_alter_productvariant_color'),
        ('order', '0012_alter_orderitem_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ad_product.productvariant'),
        ),
    ]
