# Generated by Django 5.0.1 on 2024-05-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_payment_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash On Delivery'), ('RazorPay', 'Razor Pay'), ('Wallet', 'Wallet')], max_length=100),
        ),
    ]
