# Generated by Django 5.0.1 on 2024-05-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_coupon'),
        ('order', '0017_order_order_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_coupon',
        ),
        migrations.AddField(
            model_name='order',
            name='order_coupon',
            field=models.ManyToManyField(blank=True, null=True, to='cart.coupon'),
        ),
    ]
