# Generated by Django 5.0.1 on 2024-05-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_cart_coupon_cart_coupon'),
        ('order', '0018_remove_order_order_coupon_order_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_coupon',
            field=models.ManyToManyField(blank=True, to='cart.coupon'),
        ),
    ]
