# Generated by Django 5.0.1 on 2024-05-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_payment_payment_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_status',
            field=models.CharField(choices=[('PLACED', 'Order Placed'), ('PROCESSING', 'Order Processing'), ('SHIPPED', 'Order Shipped'), ('OUT FOR DELIVERY', 'Out For Delivery'), ('DELIVERED', 'Order Delivered'), ('CANCELLED', 'Order Cancelled'), ('RETURNED', 'Order Returned')], default='PROCESSING', max_length=20),
        ),
    ]
