# Generated by Django 5.0.1 on 2024-06-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_remove_order_order_coupon_order_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FAILED', 'Failed'), ('SUCCESS', 'Success'), ('REFUNDED', 'Refunded')], max_length=20),
        ),
    ]
