# Generated by Django 5.0.1 on 2024-06-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='single_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
